/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#8b0000',
        'surface-tint': '#b52619',
        'on-tertiary-container': '#9ea9ff',
        'on-surface': '#1b1c1a',
        'secondary-container': '#fed977',
        primary: '#610000',
        background: '#fbf9f5',
        'primary-fixed-dim': '#ffb4a8',
        'on-primary': '#ffffff',
        tertiary: '#00178d',
        'on-surface-variant': '#5a403c',
        error: '#ba1a1a',
        'inverse-surface': '#30312e',
        'on-secondary-container': '#785d00',
        'error-container': '#ffdad6',
        'on-primary-container': '#ff907f',
        'on-secondary': '#ffffff',
        'tertiary-container': '#0025c8',
        'on-background': '#1b1c1a',
        'surface-container-high': '#eae8e4',
        surface: '#fbf9f5',
        'inverse-on-surface': '#f2f0ed',
        'surface-container': '#efeeea',
        'surface-dim': '#dbdad6',
        outline: '#8e706b',
        'surface-container-highest': '#e4e2de',
        'outline-variant': '#e3beb8',
        'surface-container-lowest': '#ffffff',
        secondary: '#755b00',
        'surface-container-low': '#f5f3ef',
        gold: '#C9A84C',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Be Vietnam Pro', 'sans-serif'],
        label: ['Be Vietnam Pro', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
